# Generated by Django 3.2.4 on 2021-06-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_alter_userdata_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Номер телефона'),
        ),
    ]
